### ISSUE TITLE
two character last.fm login 

### ISSUE THREAD

**Issue by ea-si** [rurza/NepTunes-Issues#10]
can't login to last.fm as my username is (really) just two characters (been on last.fm for ages)

**Comment by rurza** [comment]
hahaha :D Going to fix it with 1.4 :) Stay tuned. (< 3 weeks)

**Comment by rurza** [comment]
BTW @ea-si Sorry for that, I didn't know that there are users with so short username!

**Comment by ea-si** [comment]
@rurza no problem. well, I registered in 2004. guess all 2 character combinations are full by now .)
thanks for the quick reply. i'll wait until the next update to login

**Comment by rurza** [comment]
fixed in build `3432`

**Comment by ea-si** [comment]
works now .) thank you
