### ISSUE TITLE
Last.fm: wrong username or/and password

### ISSUE THREAD

**Issue by netopolit** [rurza/NepTunes-Issues#11]
When I try to sign in to Last.fm I get this: 
_It looks like you typed wrong username or/and password. 🤔 You can always change the password on the Last.fm website._

I'm sure username and password are correct (pasting the same to last.fm login page logs me in).

Any idea what may be causing this and how to fix it?

Thanks

**Comment by rurza** [comment]
Hi!
You're not the first one, you can fix it by resetting password on [Last.fm website](https://secure.last.fm/settings/lostpassword). 
Not sure why, my hash function is pretty straighforward.

``` obj-c
- (NSString *)md5sumFromString:(NSString *)string {
    unsigned char digest[CC_MD5_DIGEST_LENGTH], i;
    CC_MD5([string UTF8String], (CC_LONG)[string lengthOfBytesUsingEncoding:NSUTF8StringEncoding], digest);
    NSMutableString *ms = [NSMutableString string];
    for (i=0;i<CC_MD5_DIGEST_LENGTH;i++) {
        [ms appendFormat: @"%02x", (int)(digest[i])];
    }
    return [ms copy];
}
```

**Comment by netopolit** [comment]
Thanks. Resetting the password worked.
