### ISSUE TITLE
neptunes crashes

### ISSUE THREAD

**Issue by mywebcakes** [rurza/NepTunes-Issues#12]
hi 
just purchased neptunes. I noticed it crashes from time to time. The error log I can find back in the console is attached

Br,

kris
![screen shot 2016-05-15 at 13 08 42](https://cloud.githubusercontent.com/assets/19372071/15273590/bfb831f6-1a9e-11e6-8f34-e7941eaf1625.png)

**Comment by rurza** [comment]
Thanks! Going to solve it and push update ASAP.

**Comment by rurza** [comment]
@mywebcakes I think I've found it. Thanks a lot, will be fixed with 1.42

**Comment by mywebcakes** [comment]
thanks for the quick fix. I have just installed it.

Another quick question/request. It seems every time you start neptunes, spotify automatically opens. Is there a way to disable that? I don’t use spotify anymore.

BR,

Kris

**Comment by rurza** [comment]
That’s strange. I never noticed this kind of behaviour on my computers (at home and work). Are you sure you don’t have this set to “Yes”?
It’s in preferences - show advanced settings

Somehow I can't attach screenshot here so I've added it below:

**Comment by rurza** [comment]
![screen shot 2016-05-16 at 16 32 37](https://cloud.githubusercontent.com/assets/2467137/15292839/608beea6-1b85-11e6-99e5-528e50e6d25a.png)

BTW: I know, that this isn't solution but if you don't use Spotify you might consider removing it 🎯

**Comment by mywebcakes** [comment]
no, it startup is set to no.

actually I encountered another crash, it maybe related to this spotify behaviour

**Comment by rurza** [comment]
You should be my beta tester :(

Send me crash report/log :)
You can always ask Apple for refund and I'll give you a promo code to get app for free for your wasted time and precious help

**Comment by mywebcakes** [comment]
don’t bother about the beta code. the purchase was like buying you a beer…
crash log, where?

**Comment by mywebcakes** [comment]
debug hint:
it appears Spotify is in my normal user folder (/Kris/Applications), not in the system folder where most applications are
the user Kris on my mac has no admin rights

**Comment by rurza** [comment]
from Console.app, you can select it (if it exists), click with right button and choose "Reveal in Finder". Then you can attach it here from Finder.

<img width="920" alt="screen shot 2016-05-16 at 16 55 09" src="https://cloud.githubusercontent.com/assets/2467137/15293315/b5067346-1b87-11e6-823c-94b4391f65c1.png">

Thanks, for the debug hint, going to check it out!

**Comment by mywebcakes** [comment]
here you are

**Comment by rurza** [comment]
something is broken when you're answering by e-mail but don't bother - I've found it. Your hint was useful.

**Comment by rurza** [comment]
It seems that issue exists if there are copies of Spotify in both /Applications and ~/Applications (user Applications). Can you confirm this?

**Comment by mywebcakes** [comment]
no, in my case spotify exists only in ~/Applications

**Comment by rurza** [comment]
@mywebcakes can I send you "new" version of NepTunes? It should fix the issue (app won't crash but it doesn't "see" this Spotify - it detects that it's running but can't control it). I'm going to release next version with this fix (or better), but not ASAP - need to test it and I already released 3 versions this week :D

**Comment by mywebcakes** [comment]
Yes, great

---

Sent from my mobile

**Comment by rurza** [comment]
@mywebcakes I was forced to release next version - today Apple released iTunes 12.4 that crashes NepTunes (Apple fault, there is no beta program for iTunes). I've fixed iTunes 12.4 related issues and yours with Spotify. New version should be available very soon - Apple agreed to expedite review process for me.

**Comment by mywebcakes** [comment]
ok, great, thanks

**Comment by mywebcakes** [comment]
Hello

Spotify does not start anymore automatically.

But now it seems neptunes is scrobbling every track twice. See screenshot

Br,
Kris

**Comment by rurza** [comment]
@mywebcakes Unfortunately, there is no screenshot on github. Send me an e-mail: adam@micropixels.pl
