### ISSUE TITLE
Force upload of offline scrobbles

### ISSUE THREAD

**Issue by ghost** [rurza/NepTunes-Issues#14]
I'm stuck behind a proxy at work so I am only able to scrobble tracks if I switch my connection to my phone. It would be good if there were a way to force neptunes to upload all the tracks that were scrobbled while it was unable to connect. Alternatively if it does this automatically a confirmation would be nice to see. Where are the offline scrobbled tracks stored?

**Comment by rurza** [comment]
@nulloid You can turn off all Internet connections (Wi-Fi, unplug the cable etc.). 
You should see:
![screen shot 2016-05-31 at 08 58 28](https://cloud.githubusercontent.com/assets/2467137/15665982/82daa832-270e-11e6-9daf-ec434b1a4f51.png)

Then connect to your phone:
![screen shot 2016-05-31 at 09 01 46](https://cloud.githubusercontent.com/assets/2467137/15665990/8e90bcac-270e-11e6-830a-162d9277faa0.png)
![screen shot 2016-05-31 at 09 01 52](https://cloud.githubusercontent.com/assets/2467137/15666003/99ba7316-270e-11e6-8676-4018bc12522c.png)
If "hide notifications" is set in preferences, these notifications won't be displayed.
I'm not going to add some kind of "force" button - it will bloat the app. ;(
All "offline" tracks are kept in `~/Library/Containers/pl.micropixels.NepTunes/Data/Documents/NepTunesOfflineTracksToScrobble.plist`
