### ISSUE TITLE
Ability to cut extra tags in titles

### ISSUE THREAD

**Issue by Agnazar** [rurza/NepTunes-Issues#15]
Hello!

Thanks for your awesome software, it is exactly what i wanted to have time ago. Neptunes works great in most amount of cases and i'm grateful to you. 

I keep my library in clarity and right order: all tracks has correct year, no extra tags and good names. But some music in Apple Music has some trash in names (like "live", "remastered", "demo" etc). NepTunes takes that names as is. Can you allow some way to cut that kind of things from song's titles. It could be great to set up that in properties. 

By the way, the same tags won't appear in LastFM if you scrobble using built-in engines from Deezer or Spotify.  

As software engineer I see that issue easy to be done. And as user and your buyer I see that as very useful thing.

**Comment by Agnazar** [comment]
For example, if i listen to the song "And I Love Her (live)" from the album "A Hard Day's Night (remastered)" by The Beatles.

Now it will be scrobbled as "The Beatles" - "A Hard Day's Night (remastered)" from album ""

I wish to see that as "The Beatles" - "And I Love Her" from "A Hard Day's Night"

**Comment by rurza** [comment]
hm... this seems reasonable, but are you sure that everybody want this? 
There might be people, who want to scrobble everything what they listen - for example, I have full Tool discography and there is Pushit from Ænima and Pushit (live) from Salival album which are completely different tracks. 

Btw, all tracks are scrobbled with their album name, so: 
"Tool" - "Third Eye" - "Ænima" is scrobbled as "Tool" - "Third Eye" - "Ænima" and
"Tool" - "Third Eye" - "Salival" is scrobbled as "Tool" - "Third Eye" - "Salival" 
and Last.fm can match album:
![screen shot 2016-06-09 at 13 18 31](https://cloud.githubusercontent.com/assets/2467137/15927973/bf1e915e-2e44-11e6-8f3e-364d8b927e89.png) even if tracks have the same name:
![screen shot 2016-06-09 at 13 26 54](https://cloud.githubusercontent.com/assets/2467137/15928209/e17110be-2e45-11e6-9c01-aa782202e854.png)

Also, "(live)", "(demo)", etc. is very often an official name for the track, for example https://www.discogs.com/Tool-Salival/release/1594319

I don't know why Spotify and Deezer scrobblers are doing this, also I can't confirm this behavior. My primary goal for NepTunes is to make the most reliable scrobbler as possible and correct names, IMO, are necessary.

**Comment by Agnazar** [comment]
I'm totally agree with you. 

Just I saw that as good option. It will work for some users and won't work for other users. Just I know people who will want this. And seems is just simple mask alias. Some users can want to set up that.

**Comment by rurza** [comment]
@Agnazar Will be available with 1.50 update :) You can help with creating library of this tags. It will be stored on server and NepTunes will grab new version when launched

**Comment by rurza** [comment]
<img width="1280" alt="screen shot 2016-06-18 at 17 40 27" src="https://cloud.githubusercontent.com/assets/2467137/16171913/c49c7ff4-357b-11e6-9e49-34a538e48f53.png">
Done with build 3910

**Comment by Agnazar** [comment]
Hello!

Thanks so much! Can I still help with tags. Sorry for the long answer. I was in music festival. No internet in field :)

Отправлено с iPhone

**Comment by rurza** [comment]
Sure. Right now, the system is very primitive. I have a json file on my server, which NepTunes download and store every time when app was launched (will be smarter). When this option is checked, NepTunes will compare track title to contents of the json file - right now without any regular expressions (will be smarter). So i.e. if track has a "[Live]" tag - it will be removed. But if track has a "[Live at something, London]" - this will be scrobbled.

**Comment by rurza** [comment]
@Agnazar Repo address is https://github.com/rurza/Tags-to-cut but hold on with pull request - I will make it a lot smarter and then push a commit with appropriate new tags

**Comment by Agnazar** [comment]
Ok. I've got it. I'll start Exactly at the day when finally return home :)

Отправлено с iPhone
