### ISSUE TITLE
Love track on iTunes isn't being loved on Last.fm

### ISSUE THREAD

**Issue by ghost** [rurza/NepTunes-Issues#17]
I noticed that many tracks I loved on iTunes (clicked love icon while the music is being played) isn't being loved on Last.fm. But If I use the menu "Love ... on Last.fm & iTunes" then it works as expected. The universal shortcut to Love a song works too. So the only problem is when I click the Love icon in iTunes.
NepTunes version: 1.43 (3680)
iTunes version: 12.4.1.6

**Comment by rurza** [comment]
@morbec This is completely normal behavior. Unfortunately iTunes doesn't inform NepTunes that track was loved. The only way to love a track on both iTunes and Last.fm is using "Love" action on NepTunes
