### ISSUE TITLE
Crashes on occasion

### ISSUE THREAD

**Issue by kivikakk** [rurza/NepTunes-Issues#18]
Every now and then I notice that scrobbling has stopped, and only then do I realise that NepTunes isn't in my tray. I've found the following crash reports in Console.app:
- [NepTunes_2016-06-19-212403_kahekkass.crash.txt](https://github.com/rurza/NepTunes-Issues/files/322649/NepTunes_2016-06-19-212403_kahekkass.crash.txt)
- [NepTunes_2016-06-19-224354_kahekkass.crash.txt](https://github.com/rurza/NepTunes-Issues/files/322651/NepTunes_2016-06-19-224354_kahekkass.crash.txt)

I hope this might help! Looks like a double-release of an NSImage.

**Comment by rurza** [comment]
Thanks for crashlog, definitely going to nail this bug

**Comment by rurza** [comment]
I hope that I can close it right now :)

**Comment by kivikakk** [comment]
🎉 !!
