### ISSUE TITLE
Prefs window opens on login

### ISSUE THREAD

**Issue by ausgit** [rurza/NepTunes-Issues#19]
Simply, when NepTunes is set to launch on login and its menu bar icon is hidden, the preferences window opens on login.

From a usability stand point this window should only open when requiring to change a setting. I hide any third party menu bar icon which allows it, otherwise it gets quite cluttered up there!

Very low priority but I am hoping you can fix/implement this.

[NepTunes 1.43 / OS X 10.10.5]

**Comment by rurza** [comment]
@ausgit Hi! If you're not logged in to Last.fm preferences open by default to remind you, that you're not logged in. You can change this behaviour by unchecking:
<img width="624" alt="screen shot 2016-06-26 at 17 26 14" src="https://cloud.githubusercontent.com/assets/2467137/16363196/44fcf74e-3bc3-11e6-84c9-46a4730f9965.png">

**Comment by ausgit** [comment]
I'm logged into last.fm and have that option disabled. It seems to happen after hide status bar icon is enabled.

**Comment by rurza** [comment]
Hmm... I can't repeat this issue on my Mac (at work and at home). After updating to 1.50 is issue still exists?

EDIT: @ausgit ah... it seems that issue exists only on login. Definitely going to fix it.

**Comment by ausgit** [comment]
Thanks mate! Great app by the way.

**Comment by rurza** [comment]
seems fixed in latest build

EDIT: nope :( It's hard to test it in development environment.
But I remember about this problem.

**Comment by rurza** [comment]
now it should be fixed :) stay tuned for the update
