### ISSUE TITLE
"Send port for process has no send right"

### ISSUE THREAD

**Issue by tarball11** [rurza/NepTunes-Issues#20]
I'd noticed the app had been crashing quite a bit. When I looked in the console to see what was going on, it's absolutely filled with entries like the following (see also attached.):

6/29/16 4:36:07.650 PM NepTunes[1612]: AppleEvents: Send port for process has no send right, port=( port:20527/0x502f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread

![screen shot 2016-06-29 at 4 32 35 pm](https://cloud.githubusercontent.com/assets/20213470/16467938/a9873a98-3e17-11e6-8ef6-f9a6be554c5e.png)

I then noticed the new version in the app store (1.50), and installed it. Worked fine for a bit, then the album I'd been listening to finished, and as soon as I started playing a new album in iTunes, it had crashed.I'm also attaching crash reports from the pre- and post-update versions:

[NepTunesCrashReports.zip](https://github.com/rurza/NepTunes-Issues/files/340192/NepTunesCrashReports.zip)

Plus, those entries continue to appear in the console as long as music is playing. Perhaps this is related to Last.fm scrobbling, though as far as I can tell all of the tracks I was playing during this period were properly recorded by Last.fm. I'm certainly no expert, but does the message suggest that NepTunes is trying to send information and the OS is blocking it? That's.... troubling.

I'm using a MacBook Air (2011) running OS X 10.10.5, iTunes 12.4.1.6 (running in full screen mode, if that matters)

Thanks for adding more hotkeys in 1.50, by the way. Very helpful. Two feature requests: First, I'd love to have a hotkey dedicated to toggling the "album cover" window as a fast/pretty way to view the currently playing song info without it interfering with other windows. Second, it would be great to have a tiny bit more info about the current track in the album cover window -- really just the track number (e.g. 3 of 10).

**Comment by rurza** [comment]
@tarball11 Those issues with AEMachUtils.cp are "normal" for OS X 10.10 (not only for NepTunes) and the only way to fix this is by upgrading to OS X 10.11.
Thanks for the reports, definetly going to fix this

**Comment by tarball11** [comment]
Got it. Thanks!
