### ISSUE TITLE
English translation: Particles (on, to, etc) should be lowercased in menus to follow HIG

### ISSUE THREAD

**Issue by purrloftruth** [rurza/NepTunes-Issues#22]
Currently items in the menu appear in full title case, eg:

"Love [track name] On Last.fm & iTunes"
"Similar Artists To [artist name]"

<img width="305" alt="screenshot 2016-06-29 23 38 42" src="https://cloud.githubusercontent.com/assets/280610/16476176/a337378e-3e52-11e6-8dd7-425bc97286b3.png">

Whereas in the HIG, [Apple states](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/TerminologyWording.html#//apple_ref/doc/uid/20000957-CH15-SW4):

> Title style capitalization. Capitalize every word except:
> - Articles (a, an, the)
> - Coordinating conjunctions (and, or)
> - Prepositions of four or fewer letters, except when the preposition is part of a verb phrase, as in “Starting Up the Computer.”
> 
> However, always capitalize the first and last word, even if it is an article, a conjunction, or a preposition of four or fewer letters.

These should then be:

"Love [track name] on Last.fm & iTunes" and
"Similar Artists to [artist name]"

An example from Safari:
<img width="305" alt="screenshot 2016-06-29 23 34 17" src="https://cloud.githubusercontent.com/assets/280610/16476228/367601e2-3e53-11e6-9333-1a85f7260fad.png">

**Comment by rurza** [comment]
Thanks! :)

**Comment by rurza** [comment]
fixed with build `4032`
