### ISSUE TITLE
Change of song rating after playback

### ISSUE THREAD

**Issue by rhnidka** [rurza/NepTunes-Issues#26]
Hi, I have some albums rated instead of songs in my iTunes library. When I play that kind of album with NepTunes launched, the rating of all tracks changes (after the playback) from none to rating of the whole album. My english is not perfect, so in case I didn't make myself clear, I attached two screenshots which captures the change of the song rating. 

Regards
Radoslav Hnidka

![neptunes_before](https://cloud.githubusercontent.com/assets/20489235/16894348/ba525922-4b53-11e6-8dd1-0e07620e4689.png)
![neptunes_after](https://cloud.githubusercontent.com/assets/20489235/16894349/c06093c4-4b53-11e6-9324-8b14651dc3e3.png)

**Comment by rurza** [comment]
Thanks Radoslav, going to verify and let you know. Look like critical bug to fix :(

**Comment by rurza** [comment]
@rhnidka Confirmed. Dunno how and why, but will be fixed!:)

**Comment by rurza** [comment]
@rhnidka 
iTunes bug 😤.
But, I've managed to fix this – fixed in `build 4056`
Stay tuned for update in Mac App Store

![2016-08-13 15_44_01](https://cloud.githubusercontent.com/assets/2467137/17643520/c75880d6-616c-11e6-9778-526a74f3b184.gif)

**Comment by rhnidka** [comment]
Great news, many thanks for fixing this :)
