### ISSUE TITLE
Preference Request: Open when iTunes opens

### ISSUE THREAD

**Issue by errorik** [rurza/NepTunes-Issues#27]
Coversutra had this option. I would normally have this rather than open at login.

Thanks.

**Comment by rurza** [comment]
@errorik Hi Erik:) Is there any particular reason why you want this feature?

**Comment by errorik** [comment]
To me, NepTunes is only useful with iTunes.

I do not have iTunes open at Login, I only open it when I choose.

But I never want to be in a situation where iTunes is open and NepTunes is not.

I was used to this setting with CoverSutra, but it's not a deal breaker if not added. I am ok with having NepTunes open at login, but if open with iTunes _was_ available, I'd select that instead.

Thanks.

**Comment by rurza** [comment]
There are several reasons why I don't want to use this approach.  
Most importantly, it brings complexity to design. To achieve "open when" functionality, you need to create an helper app, and launch it when the user log in. This app is watching running applications, and responds accordingly. It's [fragile](https://github.com/rurza/NepTunes-Issues/issues/30) and it need to be done for Spotify and iTunes (and every player that will be added in the future). There is no significant advantage in memory usage either – on my Mac NepTunes uses 6MBs of RAM vs 3MBs for typical "Helper app" (after log in).

**Comment by errorik** [comment]
Understood.

Thank you for your prompt response and answer on the matter.
