### ISSUE TITLE
Preference Request: Album Cover for N seconds

### ISSUE THREAD

**Issue by errorik** [rurza/NepTunes-Issues#28]
I would like the Album Cover to show above all other windows, but only for 1-5 seconds on Play/Pause/Next/Prev/Rating actions.

Can this be added as a preference?

Also, a setting to disable the cover blurring animation that takes place on actions Play/Next/Prev actions... I just want to see the cover and don't want the blur overlay with the album info.

**Comment by ArNz8o8** [comment]
+1 for an option to turn off the album info overlay.

**Comment by rurza** [comment]
@ArNz8o8 @errorik 
slightly modified version of your idea will be in 1.60:
– simple mode, where there is only cover, without controls and without label with artist name on the bottom,
– notifications mode, where cover will float above all windows for ~4 sec (with overlay) and returns to original position.
Your proposition with notifications without overlay (where is artist name and track name) is useless IMO. Imagine that you're listening album. You will see notification without any useful information and you will see the same cover x times for every track in album. Makes sense? For me it doesn't. But, I hope you'll like it :)

stay tuned for the release
