### ISSUE TITLE
Can not set Hotkey "Control-Command-Space", already in use

### ISSUE THREAD

**Issue by errorik** [rurza/NepTunes-Issues#29]
I get a message stating:

> The key combination ⌃⌘Space cannot be used
> This combination cannot be used because it is already used by a system-wide keyboard shortcut.
> If you really want to use this key combination, most shortcuts can be changed in the Keyboard & Mouse panel in System Preferences.

I indeed do have a system keyboard shortcut for the Keyboard Character / Emoji viewer for this key combo. However, I have looked in the System Preferences and can not find a method to turn it off.

Is there a way for you to show this warning, but then include an option for Neptunes to take over the keyboard shortcut / hotkey and override the system default?

**Comment by rurza** [comment]
Nope, sorry :(

**Comment by errorik** [comment]
Thank you.
I have found a workaround.
If anyone else is interested... I set my NepTunes hotkey for Play/Pause to ⌃⌘P [NepTunes preferences as such](http://i.imgur.com/N3o99oa.png), then used a keyboard remapping app Karabiner to remap ⌃⌘Space to ⌃⌘P with the following XML:

`
    <item>  
        <name>Custom Remap for NepTunes PlayPause</name>  
        <identifier>PRIVATE.neptunes.playpause.remap</identifier>  
        <autogen>  
            __KeyToKey__  
            KeyCode::SPACE, ModifierFlag::CONTROL_L | ModifierFlag::COMMAND_L,  
            KeyCode::P, ModifierFlag::CONTROL_L | ModifierFlag::COMMAND_L  
        </autogen>  
    </item>
`
