### ISSUE TITLE
Menu sometimes shows several "Source" options

### ISSUE THREAD

**Issue by zacharykeeping** [rurza/NepTunes-Issues#30]
Not exactly sure what's causing this, but sometimes I get several repeating "Source" options in the dropdown menu (see image). Restarting the application fixes the issue temporarily.

<img width="227" alt="screen shot 2016-07-20 at 2 31 41 pm" src="https://cloud.githubusercontent.com/assets/11418832/16975327/851ebf60-4e88-11e6-8e1c-d9469a318f88.png">

**Comment by rurza** [comment]
@ZKeeping Known issue, will be fixed with next update (~2 weeks, right now I'm busy with Pokéssenger)

**Comment by rurza** [comment]
@ZKeeping  fixed in latest build :)
