### ISSUE TITLE
Status bar hidden, interacting with Desktop Album Cover opens preferences

### ISSUE THREAD

**Issue by neeklamy** [rurza/NepTunes-Issues#31]
**Steps to reproduce:**
1. Set NepTunes to **Hide status bar icon**.
2. Play a song so that the Desktop Album Cover appears.
3. Switch to a different application (iTunes for example), but leave the Album Cover visible.
4. Interact with the Album Cover in some way, for example: change the sound volume.
5. NepTunes preferences window pops open.

OS X 10.11.6, NepTunes 1.50

**Screen capture of bug in action:**

![neptunes-desktop-contextual-menu-bug](https://cloud.githubusercontent.com/assets/155358/16988702/31b64bc6-4e89-11e6-953d-f852fb9d6605.gif)

**Notes:**
- As you can see from the brief screen capture, I am logged into and scrobbling just fine from NepTunes.
- Re-enabling the status bar icon stops the bug from appearing.
- Another application has to be in the foreground, if NepTunes already has key focus, the bug won’t show itself.
- Even just clicking on the Album Cover and moving the cover around causes the preferences window to appear.
- Right-clicking on the Album Cover to bring up the contextual menu works fine.
- There isn’t any error messages related to this in Console.

Possibly related to #19?

**Comment by rurza** [comment]
@neeklamy yep, will be fixed with the next update :)

**Comment by rurza** [comment]
fixed  in `4167` :) stay tuned for the update
