### ISSUE TITLE
Issues with multiple displays

### ISSUE THREAD

**Issue by rurza** [rurza/NepTunes-Issues#32]
> @neptunesformac Will there also be a fix for the desktop widget not staying put? If I skip a song, or pause/play, it moves monitors.
> 
> @neptunesformac Of course now that I go to video it, it won’t do it. Not sure the cause, but the position resets from monitor A -> mon B

**Comment by JadoJodo** [comment]
It may be an issue w/ the primary display, as that's the one it keeps moving back to. I'm still not sure what triggers it, but I will have to move it back into position frequently.

**Comment by rurza** [comment]
@JadoJodo 

EDIT123123123:
Ok, I think I've found answer. Window with cover appear on currently active space. Going to fix this.

Old answer:
EDIT: I think I've found issue, that you're talking about. Not sure how to fix, because it looks like NepTunes cover window don't remember it's position as it should.
EDIT2: Machine restart helped. I think that it's related to some problems with [defaults](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/defaults.1.html), which is used to save window state etc. In recent OS X versions Apple uses cache to minimize write/read operations. But, if you use cache, sooner or later there are always some issues with it. [Documentation](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSUserDefaults_Class/index.html) says:

> NSUserDefaults caches the information to avoid having to open the user’s defaults database each time you need a default value. The synchronize method, which is automatically invoked at periodic intervals, keeps the in-memory cache in sync with a user’s defaults database.

My own internal implementation of settings always send `synchronize` message to defaults (when it makes sense of course) BUT I can't control saving window state/position (I think, maybe I'm wrong; this is managed by OS itself). In my case, OS X reboot helped. Maybe it will be better in upcoming macOS Sierra.

EDIT3: BTW issue exists when window with cover disappear and then appear (ie when you stop music and play it). I'm at work now and don't have access to source code, but maybe I am able to fix it. Stay tuned :))

ORIGINAL ANSWER:
hm... maybe you have iTunes on second display? Because double-click (even slow, like fast changing tracks by clicking next and next) on cover (I suppose that NepTunes should ignore clicks on buttons – that's the upcoming fix) bring iTunes to front.
My example:
![screen shot 2016-08-17 at 09 43 18 2](https://cloud.githubusercontent.com/assets/2467137/17728320/0fd8f698-645f-11e6-9267-818b4884e70c.png)
![screen shot 2016-08-17 at 09 43 18](https://cloud.githubusercontent.com/assets/2467137/17728324/1387ecd6-645f-11e6-936a-aff0d4144c35.png)
Display from the second screenshot (which is my main display) has two spaces - one for most used apps, second for iTunes, Twitter etc. But NepTunes cover is used on the secondary display (first screenshot). So if I double-click on cover (or change track very fast) it will bring iTunes to front and switch space on my main display. That's normal behaviour – but yeah, it can feel a little bit strange. You can verify this by unchecking this option:
![screen shot 2016-08-17 at 10 25 51](https://cloud.githubusercontent.com/assets/2467137/17729564/16aac9be-6465-11e6-9964-f8090df45082.png)

**Comment by rurza** [comment]
@JadoJodo fixed :) stay tuned for the update (~week)

**Comment by JadoJodo** [comment]
Thanks!
