### ISSUE TITLE
Album Cover keeps moving back to primary display when selecting new album in iTunes.

### ISSUE THREAD

**Issue by GadgetComa** [rurza/NepTunes-Issues#33]
I have the album cover display showing on my secondary monitor. When I switch albums (or songs) in iTunes, the album cover jumps back to the primary display. I've tried changing the setting for where the window should appear in preferences, but it moves regardless of the setting.

**Comment by rurza** [comment]
@GadgetComa Hi! Thanks, already acknowledged in https://github.com/rurza/NepTunes-Issues/issues/32
