### ISSUE TITLE
v1.60 cannot start scrobbling

### ISSUE THREAD

**Issue by piodio** [rurza/NepTunes-Issues#34]
El Capitan 10.11.6, iTunes 12.5.1.21

v1.60 does not start scrobbling, no album window.
If I re-launch neptune during iTunes playing it starts scrobbling just current now playing song once then album window goes to disappear and scrobbling stops.

I'm not using simple mode but small cover and notification option are turned on.

**Comment by rurza** [comment]
hm... very very strange. I still don't get it – why don't you see cover?

**Comment by rurza** [comment]
Go to Finder and press CMD+SHIFT+G, then paste this: `~/Library/Containers`
![screen shot 2016-09-18 at 19 58 13](https://cloud.githubusercontent.com/assets/2467137/18617846/3fa17302-7dda-11e6-8f3b-f3a9cc9c9546.png)
and press Go (or equivalent in your language). Delete `pl.micropixels.NepTunes` folder. This will reset NepTunes to default state. Maybe this will help

**Comment by rurza** [comment]
@piodio  
Btw, you can always poke me on Twitter @rurza if you have an account. I treat your problem with very, very high priority so let me know if anything changed.  
Btw 2. I didn't change anything on the scrobbler side of the app in 1.60

**Comment by piodio** [comment]
Thank you for reply. But still not lucky.

I created for test a new clean library (with about 20 songs) and NepTunes works perfectly.
This is so strange. My current library has about 33,000 tracks. I don't think library size is problem.

Neptunes cannot be triggered newly started song. 
- Launch NepTunes, then launch iTunes, Play a song: No scrobbling, No cover window.
- Launch iTunes, Play a song, then launch NepTunes: Scrobbling starts, cover windows is popup but when the next song is started NepTunes stops scrobbling and cover window is closed.

Any recommended way to investigate it?

Thanks.

**Comment by rurza** [comment]
Check if you have proper tags in tracks – NepTunes requires min. track and artist names in tags. You can verify them, by clicking on track (that isn't scrobbled) with secondary mouse button and choosing "Get Info"
![screen shot 2016-09-19 at 13 48 03](https://cloud.githubusercontent.com/assets/2467137/18631015/f550bf4c-7e6f-11e6-871c-c9ff5109fc9f.png)

Also: Does your user is an administrator? What's the location of NepTunes on disk? Should be in `/Application`

Also 2: There is special Debug Mode in NepTunes; in Terminal.app (you can copy-paste code below)
`defaults write pl.micropixels.NepTunes debugMode YES`

NepTunes will print everything it does in Console.app (both Terminal and Console are built-in applications) like on screenshot : 
![screen shot 2016-09-19 at 13 54 03](https://cloud.githubusercontent.com/assets/2467137/18631136/8a6ad2e8-7e70-11e6-93dd-f6aacc9c5441.png)

To turn off debug mode paste code below to the Terminal:
`defaults write pl.micropixels.NepTunes debugMode NO`

**Comment by piodio** [comment]
The problem is solved.

I rolled back "iTunes Library.itl" to a previous version which was created on 13th Sep. (created on just before updated to  iTunes 12.5.1.21). And now everything works fine again. Still I don't know reason why but am happy anyway. Maybe iTunes database went wrong during the updating.

I appreciate your kind advices and detailed descriptions.
Good lucks and cheers.
