### ISSUE TITLE
Feature: 'Cut extra tags' in album titles tags 

### ISSUE THREAD

**Issue by piodio** [rurza/NepTunes-Issues#35]
Is there any chance to add option of 'Cut extra tags in album titles tags'?
eg, [2001 UK re-release], [EP], (Special Limited Version), (Remastered)

Thank you so much.

**Comment by rurza** [comment]
Done, to refresh the list go to preferences and un-check and check again "Cut extra tags" :)

**Comment by piodio** [comment]
Thank you but it doesn't cut extra tags of _Album_ Titles, It only works on song(track) titles.
![2016-09-19 5 28 56 pm](https://cloud.githubusercontent.com/assets/1523072/18628564/d81f3b52-7e9b-11e6-8a1b-eea5513e64f9.png)

**Comment by rurza** [comment]
Hahahaha, never thought about it :)
Wait for next update, I will add this feature

**Comment by rurza** [comment]
@piodio added, stay tuned for App Store version :)
