### ISSUE TITLE
iTunes keeps reopening after closing

### ISSUE THREAD

**Issue by ArNz8o8** [rurza/NepTunes-Issues#36]
Since macOS Sierra (or iTunes 12.5..) iTunes keeps reopening after i close it with cmd+q. I have to force quit it to get rid of it opening again. When I turn NepTunes off, the problem of iTunes reopening after closing is not there.

Seems to be a neptunes problem, or am I wrong?

**Comment by rurza** [comment]
@ArNz8o8 I don't have this issue on my Macintosh computers, but it can appear on slower machines. What machine do you have?

I can add, that this issue happens when iTunes close slooooowly (press cmd+q and you will see the dock icon for 3-4s)

**Comment by ArNz8o8** [comment]
Well, I have a iMac 27" 5K from late 2014. With an i7 cpu, AMD R9 285x gpu and 16Gb of ram installed. Not too slow I reckon?

On ma, sep. 26, 2016 at 22:00, Adam notifications@github.com wrote:
@ArNz8o8 [https://github.com/ArNz8o8] I don't have this issue on my Macintosh computers, but it can appear on slower machines. What machine do you have?

**Comment by ArNz8o8** [comment]
Also. iTunes closes as soon as I cmd+q it. Dock icon is gone and then it just starts again

**Comment by rurza** [comment]
definitely not slow machine ;)  
thanks, going to fix this (it happened on my Mac too :D)

**Comment by ArNz8o8** [comment]
Ahw great. Thanks man! I love this little app. Hope to see it fixen soon ☺️

**Comment by ArNz8o8** [comment]
Fixed\* (autocorrect)

**Comment by rurza** [comment]
Thanks :) If I find the issue you can expect an update this week :)

**Comment by hostep** [comment]
I also noticed the last couple of months something similar, never thought it had anything to do with Neptunes, but after reading the above, it started ringing bells.

So, I usually close down most of my applications, including iTunes, and then close my Macbook so it goes into sleep mode. But when reopening my Macbook a couple of hours later, lo and behold, iTunes magically restarted itself.

Can this be the same bug I see?
I'm using El Capitan and I've seen it happening on both iTunes 12.4 and 12.5

**Comment by rurza** [comment]
@hostep @ArNz8o8  fixed :) stay tuned for the update

**Comment by ArNz8o8** [comment]
Eh wow, that was fast.. great, thanks!

**Comment by ArNz8o8** [comment]
I hope this finds a way to you @rurza but I just got the 1.6.1 update from the app store, and it works flawless.. Thanks a bunch!

**Comment by rurza** [comment]
Thanks for your feedback!

Adam

Wysłane z iPhone'a

Dnia 28.09.2016 o godz. 18:22 ArNz|8o8 notifications@github.com napisał(a):
