### ISSUE TITLE
Sync iOS device scrobbles on sync (like the official last.fm app does)

### ISSUE THREAD

**Issue by warthog3** [rurza/NepTunes-Issues#39]
I know you have plans to develop an iOS app.. any chance you'd also consider including this feature in NepTunes?

Your client would be perfect (in my opinion) if it had this feature.

**Comment by jaknudsen** [comment]
Would love scrobbling of iPod listens!

**Comment by rurza** [comment]
idea is simple and great but it's not possible with current iTunes to do it reliably :(

**Comment by irfus** [comment]
Any chance this could still be considered? The official app still does this, I believe, though that is unreliable on a whole different level. I'm using an iPod shuffle, so have no other way to scrobble. Another scrobbling app I used to use earlier (now defunct) used to keep track of play counts to do this. Upon sync, all tracks with an updated play count would be scrobbled. It'd be fine even if the time of playing isn't captured accurately.

**Comment by rurza** [comment]
Hey,
nope. The app is pracitcally dead in terms of new „big” features.
