### ISSUE TITLE
NepTunes keeps launching Spotify in the background

### ISSUE THREAD

**Issue by cdzombak** [rurza/NepTunes-Issues#41]
Running NepTunes 1.6.3 on macOS Sierra 10.12.5.

I notice that Spotify keeps launching in the background even when I have not been listening to any music in iTunes or Spotify. This happens after a little while — I don't know exactly how long, but on the scale of every ten minutes or so — and especially after I unlock the screen after being away for a few minutes.

When I quit NepTunes the problem goes away.

In NepTunes preferences, I have unchecked "Scrobble from Spotify" an d"Integration with Spotify and iTunes," yet the problem persists.

**Comment by rurza** [comment]
Thanks! Sure, I will fix it with the next update (which I will release in 2 weeks)

**Comment by cdzombak** [comment]
@rurza did you have a chance to look into this?

**Comment by rurza** [comment]
Nope, but I will now (100%). I'm really, really sorry :(

**Comment by cdzombak** [comment]
No apologies needed; there are worse problems to have 😄 

FWIW, in the AppleScript world I've found [this thread](https://stackoverflow.com/questions/16064957/how-to-check-in-applescript-if-an-app-is-running-without-launching-it-via-osa) useful when addressing similar problems.

**Comment by cdzombak** [comment]
Thanks! I'll try this latest update.
