### ISSUE TITLE
Scrobbled problems

### ISSUE THREAD

**Issue by vpell** [rurza/NepTunes-Issues#42]
I'm a new user and though i like the UI and features so far, i have a major problem: when listening to my iTunes Library, a lot of tracks are not scrobbled. I don't see the pattern, it just seem random.
I had set the scrobbling at 80 % of the track and just get it back to 50 % to test.
The Recent Tracks list in the app is ok though.
And right now a long track has been scrobbled twice…

MacOS 10.11.6
iTunes 12.6.2.20

**Comment by rurza** [comment]
Hey @vpell 
Are you sure that you have ID3 tags in your music. Does cover that shows now playing track is updating correctly?

**Comment by vpell** [comment]
Everything is carefully tagged and covers are showing in NepTunes.

The thing is that for every album i listen (i'm an old album listener ;)) some tracks are missing on my last.fm library, but are listed in NepTunes Recent Tracks.
For the last couple of hours i have switched back to the official Last.fm client: no tracks are missing.
I'll try again NepTunes tomorrow (it's 20:00 in Paris, France) as i really want to use your app.
My Last.fm user is "vpell" and i'm willing to help you debug this if possible.

Thanks for your help

**Comment by rurza** [comment]
@vpell 
There is a special Debug Mode in NepTunes; in the Terminal.app (you can copy-paste code below)
`defaults write pl.micropixels.NepTunes debugMode YES`

NepTunes will print everything it does in the Console.app (both Terminal and Console are built-in applications) like on the screenshot:

![screen shot 2017-09-13 at 20 32 30](https://user-images.githubusercontent.com/2467137/30394200-abf59d68-98c2-11e7-81f9-fb4893cfc6cd.png)

I have filters turned on to see the logs from NepTunes and to cut the garbage logged by system libraries: CFNetwork, AppleJPEG, Security.

**Comment by vpell** [comment]
OK, i'll do that.

**Comment by vpell** [comment]
Hi,

i think i nailed the problem.
When a track is playing i often change some track tags (comments, notation, like).
When looking at the logs, i see that each tag change trigger those 4 lines below is 3 successive tag changes) :

> 17/09/2017 09:35:05,453 NepTunes[31018]: Notification sent from Music Player
> 17/09/2017 09:35:05,454 NepTunes[31018]: Timers invalidated
> 17/09/2017 09:35:06,958 NepTunes[31018]: Updating Recent Tracks menu
> 17/09/2017 09:35:10,458 NepTunes[31018]: Scrobble time for track Générique by Alain Goraguer with duration of [44.512001s] is 22.256001
> 17/09/2017 09:35:14,816 NepTunes[31018]: Notification sent from Music Player
> 17/09/2017 09:35:14,817 NepTunes[31018]: Timers invalidated
> 17/09/2017 09:35:16,321 NepTunes[31018]: Updating Recent Tracks menu
> 17/09/2017 09:35:19,822 NepTunes[31018]: Scrobble time for track Générique by Alain Goraguer with duration of [44.512001s] is 22.256001
> 17/09/2017 09:35:22,523 NepTunes[31018]: Notification sent from Music Player
> 17/09/2017 09:35:22,523 NepTunes[31018]: Timers invalidated
> 17/09/2017 09:35:24,029 NepTunes[31018]: Updating Recent Tracks menu
> 17/09/2017 09:35:27,531 NepTunes[31018]: Scrobble time for track Générique by Alain Goraguer with duration of [44.512001s] is 22.256001

The thing is the timer for the scrobble time is reset each time, starting from the time of last tag change, but the 50% time lapse before scrobbling stay the same (50% of the track length — in the case above 22.256001). So, regularly, the scrobble time is missed.

This problem is not happening when i don't change tags during play or when the tag changes are all made during the first half of the song (if the Neptunes settings are at 50% of course).

**Comment by rurza** [comment]
Cool :)

**Comment by vpell** [comment]
Hi,
Not sure what's cool?
Did you (will you) fix the problem i encounter or do you consider that what i found is the correct behavior?

**Comment by rurza** [comment]
It's a correct behaviour.

**Comment by vpell** [comment]
OK, fair enough, i'll get back the the official Scrobbler as i didn't have this problem with it. Too bad, i prefered your app ;)
But, if i may, what is the purpose of this behavior? Even if the tags are updated during play, the track should be able to be scrobbled no matter what.
Tell me if i'm wrong: if the starting time of reference is not reset each time a tag change happen, the problem should disappear.

**Comment by rurza** [comment]
Not sure why Last.fm allows that. When you change the tag, iTunes is sending a message to NepTunes (and Last.fm) that track has changed. 
Sure, I could remember the last track, compare the all metadata, playback time and decide, if the change should be ignored because you just changed the tags or maybe you pushed "previous" button on iTunes. But seems to me that this is over complication.
The app is almost 3 years old, you're the first one with this problem, so it's really hard for me to believe that it's a huge problem for the rest of users (and I'm using the app as well) and as far I know, NepTunes is much more reliable scrobbler than official Last.fm client.

**Comment by vpell** [comment]
No luck for me then, back to Last.fm Scrobbler :)
