### ISSUE TITLE
Can't login despite correct username and password

### ISSUE THREAD

**Issue by frac89** [rurza/NepTunes-Issues#43]
As the title says. Maybe my password is too long (20 characters)?

**Comment by rurza** [comment]
Hey!
Some users had this issue before. I don't have any idea why some passwords doesn't work. Solution in all cases is to change it. Let me know if it did help :)

**Comment by frac89** [comment]
Yeah it works now, thanks. Apparently my old password was not fit for the new security policy, that must have confused your app.
