### ISSUE TITLE
Extra Large Album Covers

### ISSUE THREAD

**Issue by Cearul** [rurza/NepTunes-Issues#44]
I would love to see an option for even larger album covers. The album art on my iMac 27" looks too small (that's just my opinion) but I've love to see an option for 500 x 500px.
Thanks!

**Comment by rurza** [comment]
Hey, current large size is compromise – the app supports retina displays too, so artworks are already 500x500. Unfortunately artworks are often not available even in this size, so larger cover would look like shit on the screen :(

**Comment by Cearul** [comment]
That's a shame : ( I usually source high quality album covers for my music in iTunes, but I can understand where you're coming from for Spotify.

**Comment by rurza** [comment]
Thanks for understanding!
Another example – if you stream music from Apple Music (and it's not in your iTunes library) and iTunes sends notification that track has changed, there is no cover attached :/ So NepTunes is looking for the cover in iTunes and Last.fm :/
