### ISSUE TITLE
Neptunes keeps crashing

### ISSUE THREAD

**Issue by frac89** [rurza/NepTunes-Issues#46]
Since the last iTunes update, Neptunes closes itself and doesn't even warn about it. I don't know if the two things are connected, but it has happened two times only today. I'm using a 2008 Macbook with the 10.11.6 OS.

**Comment by rurza** [comment]
what version of NepTunes do you have?
1.65 should be rock solid:
<img width="1043" alt="screen shot 2017-11-07 at 20 33 10" src="https://user-images.githubusercontent.com/2467137/32513618-eeaebc9e-c3fa-11e7-835e-1509ad78ac99.png">

**Comment by frac89** [comment]
I tried the latest version of Neptunes (had to reinstall it because the App Store won't update it on its own) and everything works like a charm so far. Thanks for the tip!
