### ISSUE TITLE
Additional keyboard shortcuts [enhancement]

### ISSUE THREAD

**Issue by kaassouffle** [rurza/NepTunes-Issues#47]
Additional keyboard shortcuts that I would find very useful are:

- Shortcut to show current track (now playing). 
I have the album cover on my desktop, but usually it is hidden behind a few windows. It would be great to have a quick way to check the song that is currently playing.
(Could be 'show latest osx notification' or could bring the album cover to front for a few seconds)

(I do this now using a service I made with applescript, it shows an osx notification of the song playing. But wouldbe great if Neptunes handles this.)

- Shortcut to 'bring player to front'
Sometimes I want to do edit a playlist, or hit repeat or something. Would be great to have Neptunes help with this by providing a shortcut to the program that is playing music.

**Comment by rurza** [comment]
cool ideas!
soon!

**Comment by rurza** [comment]
Done.
Wait for the 1.70 update :)
