### ISSUE TITLE
Can't set ctrl-alt-cmd-l for love a track

### ISSUE THREAD

**Issue by monsieurm** [rurza/NepTunes-Issues#48]
Hi, 

I have two Mac, on the first one, I can set ctrl-alt-cmd-l for loving a track, but on the another Mac I can't set this shortcut. I can't set more two special keys. It's work fine with ctrl-alt-l and I don' know why I can't set the same shortcut.

Same Mac model
Same OS (High Sierra)

Thanks

**Comment by rurza** [comment]
Probably because some other app already registered the same shortcut
