### ISSUE TITLE
Disabling Spotify Scrobbling

### ISSUE THREAD

**Issue by malulo95** [rurza/NepTunes-Issues#51]
Now that last.fm changed the way to scrobble from spotify, it would be useful to have an option to disable spotify scrobbling to avoid double scrobbles

**Comment by rurza** [comment]
Hey, 
you can already do it:

![screen shot 2018-05-14 at 13 59 40](https://user-images.githubusercontent.com/2467137/39996233-202ac55c-577f-11e8-940c-4c7ba6d80a6e.png)
