### ISSUE TITLE
Display Track Info on Hover in Simple Mode

### ISSUE THREAD

**Issue by clayneh** [rurza/NepTunes-Issues#52]
I really prefer the look of Simple Mode, but it really inhibits the functionality of the app. While in Simple Mode, it'd be great if on hover the player appeared as well as the Track Name, Album Name, and Artist Name.

Something like this:
![mockup](https://user-images.githubusercontent.com/42246652/43912310-797baa36-9bc7-11e8-98c0-3fbcec58aa03.png)

**Comment by rurza** [comment]
You have a point!

**Comment by rurza** [comment]
Hey! With upcoming update you can hover the cover to see the controls.
So partially it's what you requested (without artist info).
