### ISSUE TITLE
Support for macOS Catalina?

### ISSUE THREAD

**Issue by jaknudsen** [rurza/NepTunes-Issues#59]
macOS 10.15 Catalina does not have an iTunes app. Are you planning to support the new Music app?

**Comment by jbwharris** [comment]
+1 on this one. Just installed the Catalina Beta and am now looking for a stopgap scrobbler.

**Comment by rurza** [comment]
> macOS 10.15 Catalina does not have an iTunes app. Are you planning to support the new Music app?

Yes ;)

**Comment by jaknudsen** [comment]
Great news! :)

**Comment by skyzyx** [comment]
GM was released yesterday.

**Comment by Movisivi** [comment]
Since @rurza has been afk for a while, here's a working app https://github.com/yungtry/CatalinaScrobbler

**Comment by rurza** [comment]
Hey, NepTunes 1.70 is released, thank you all for the support and sorry for the delay :)

https://apps.apple.com/us/app/neptunes-for-lastfm/id1006739057?l=pl&mt=12
