### ISSUE TITLE
Sharing on Twitter or Facebook is not possible

### ISSUE THREAD

**Issue by DaLucy65** [rurza/NepTunes-Issues#60]
Tweeting the currently playing song is not possible as the menu entry is greyed out. Same goes for Facebook.
Version is 1.66 (4602)
![Screenie](https://user-images.githubusercontent.com/53568049/63187777-fec10700-c05f-11e9-858e-6c4b1f9f031c.png)

**Comment by rurza** [comment]
Hey, Apple removed this functionality in Mojave, that's why is greyed out. I know that it shouldn't be visible in the first place but I didn't update the app for a while and I still "support" the older versions of macOS :)
