### ISSUE TITLE
NepTunes has stopped scrobbling entirely

### ISSUE THREAD

**Issue by arbitrarily** [rurza/NepTunes-Issues#62]
Mac OS 10.14.6 (18G87), latest Neptunes. Unable to scrobble anything from iTunes, client doesn't show on desktop. I've reset, relinked to Last.fm, reinstalled. 

Errors/Warnings I get in console:

27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 201 vs 310, 512, <private>

![image](https://user-images.githubusercontent.com/899183/67793019-83f96c80-fa50-11e9-8295-bc32a6cafd7d.png)

Any help is much appreciated,
Marko

**Comment by rurza** [comment]
Hm… those messages are generated by the OS. Does the NepTunes is selected in System Preferences -> Security and Privacy -> Automation?

**Comment by arbitrarily** [comment]
Thank you so much, that was it exactly.

Much appreciated!
Marko
