### ISSUE TITLE
Not Scrobbling/Loving (Big Sur Music 1.1.0.234)

### ISSUE THREAD

**Issue by ErikVeland** [rurza/NepTunes-Issues#69]
Logs all appear normal (I think?), but no tracks show up under my profile on Last.fm.

https://www.last.fm/user/ErikVeland

<img width="1901" alt="image" src="https://user-images.githubusercontent.com/251715/92435589-111b5f00-f1e6-11ea-9d2b-6263e52d5a51.png">

I thought it might have been AdGuard, but even stopping it hasn't made a difference.

**Comment by mountainash** [comment]
NepTunes is  is working for me (macOS 11.0.1), but I had to enable "Automation" (System Preferences > Security & Privacy > Privacy (tab) > Automation > NepTunes.app (check) Music)

**Comment by rurza** [comment]
The app works on Big Sur, unfortunately it requires the permission and sometimes Last.fm servers don't work :(
